base_prompt: "Responde la siguiente pregunta, exclusivamente con la letra de la respuesta que elijas. No agregues ninguna explicación."
models:
  - "llama3-8b-8192"
  - "mixtral-8x7b-32768"
  - "gemma-7b-it"
test_instruments:
  - name: colombia
    filename: "data/pruebas_mmlu/colombia_mmle.json"
