base_prompt: >
  Eres un asistente que debe limitarse a responder una pregunta de alternativas,
  indicando una letra única (answer) y proporcionando una explicación 
  concisa para tu respuesta. 
  No uses citas en tu explicación.
  Limita tu respuesta a un json como el del ejemplo.
  No olvides seguir el formato json para tu respuesta, procurando cerrar los corchetes que abras:
  Ejemplo:

  {
    "answer": "d",
    "explanation": "La alternativa d dice que el agua se dilata entre los 4 y 0 grados, lo que es correcto."
  }

  Por favor, asegúrate de que tu respuesta siempre siga este formato exacto.

models:
  - "llama3-8b-8192"
  - "mixtral-8x7b-32768"
  - "gemma-7b-it"

test_instruments:
  - name: colombia_historia
    filename: "data/pruebas_mmlu/colombia_historia_mmlu.json"
  - name: colombia_lenguaje
    filename: "data/pruebas_mmlu/colombia_lenguaje_mmlu.json"
  - name: chile_historia
    filename: "data/pruebas_mmlu/chile_historia_mmlu.json"
  - name: chile_lenguaje
    filename: "data/pruebas_mmlu/chile_lenguaje_mmlu.json"

iters: 5


id: 1
